### PR TITLE
Implementation for ddnss(.de)

### PR DESCRIPTION
**Pull request by seriouz**
Implementation for ddnss(.de)

### CODE REVIEW

**Comment by mholt** [comment]
Very cool, thanks!

I've created the repo here and added you to it: https://github.com/caddy-dns/ddnss

Feel free to push :+1:

**Comment by seriouz** [comment]
Thanks! I pushed the repo and made a test run with `xcaddy build --with github.com/caddy-dns/ddnss` and it worked perfectly!

**Comment by seriouz** [comment]
@mholt Will the addon be available under https://caddyserver.com/download and have i to do anything that it appears there?

**Comment by mholt** [comment]
@seriouz To add it to our site, just create an account there, then claim your package in your account :)

**Pull request closed without merging**
